# Generated by Django 3.1 on 2021-06-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rejected',
            field=models.BooleanField(default=True),
        ),
    ]
