# Generated by Django 3.1 on 2021-06-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_job_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='not-listed', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
